# Numpy
- Introduction to Numpy Array Creation Printing Arrays, Basic Operations- Indexing, Slicing and Iterating
- Shape Manipulation - Changing shape,
- stacking and spliting of array Vector stacking
- Arithmetic operation, Matrix multipliacation
- Filtering values from an array
- Applying statistic function over array (to whole elements or row wise or column wise)
- Exercise

In [1]:
import numpy as np

In [3]:
print(len(dir(np)))

616


In [4]:
a = np.array([])
print(a)

[]


In [6]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [8]:
print(a)
print(a.dtype)
print(a.size)
print(a.shape)
print(a.ndim)
print(a.itemsize)

[[1 2 3]
 [4 5 6]]
int32
6
(2, 3)
2
4


In [13]:
a = np.array([[1,2,3],[4,5,6.]])
print(a)
print(a.dtype)


[[1. 2. 3.]
 [4. 5. 6.]]
float64


# change the dtype

In [11]:
a = np.array([[1,2,3],[4,5,6.]],dtype="int16")
print(a)
print(a.dtype)
print(a.itemsize)


[[1 2 3]
 [4 5 6]]
int16
2


In [15]:
a = np.array([[1,2,3,4],[4,5,6.]])
print(a)
print(a.dtype)
print(a.itemsize)


[list([1, 2, 3, 4]) list([4, 5, 6.0])]
object
8


# Break , will b eback by 2:05PM

# Basic operations

In [18]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,1],[2,2]])
print(a)
print(b)
print("#"*20)
print(a+b)
print(a-b)
print(a*b)
print(a**b) # a power  b

[[1 2]
 [3 4]]
[[1 1]
 [2 2]]
####################
[[2 3]
 [5 6]]
[[0 1]
 [1 2]]
[[1 2]
 [6 8]]
[[ 1  2]
 [ 9 16]]


# dot product

In [20]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,1],[2,2]])
print(a)
print(b)
np.dot(a,b)

[[1 2]
 [3 4]]
[[1 1]
 [2 2]]


array([[ 5,  5],
       [11, 11]])

# arange

In [21]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# reshape

In [26]:
a = np.arange(10)
# a.reshape(5,2)
# a.reshape(2,5)
a.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

#### random

In [30]:
r = np.random.randint(1,50,30).reshape(10,3)
r

array([[ 1, 33, 25],
       [29, 31, 20],
       [34,  7, 41],
       [42, 39, 11],
       [ 8, 38, 48],
       [29,  4, 41],
       [11, 14, 23],
       [32, 22, 19],
       [ 4, 45, 48],
       [43, 45,  2]])

In [31]:
r = np.random.randint(1,7,100)
r

array([3, 1, 6, 6, 4, 1, 3, 1, 5, 2, 1, 3, 3, 1, 1, 3, 3, 2, 6, 5, 5, 5,
       5, 4, 3, 6, 4, 4, 4, 2, 4, 5, 1, 1, 2, 6, 2, 6, 6, 4, 5, 4, 3, 3,
       2, 1, 5, 3, 1, 1, 4, 5, 3, 4, 1, 6, 3, 3, 3, 5, 4, 6, 4, 4, 2, 3,
       1, 1, 2, 5, 6, 4, 5, 5, 6, 1, 6, 5, 6, 6, 1, 6, 4, 2, 5, 6, 3, 4,
       6, 5, 3, 3, 4, 3, 4, 3, 1, 3, 1, 1])

# 3 -dim array

In [34]:
r = np.random.randint(1,10,27).reshape(3,3,3)
r

array([[[7, 2, 6],
        [6, 4, 9],
        [6, 4, 6]],

       [[7, 6, 9],
        [4, 6, 8],
        [5, 3, 6]],

       [[4, 7, 8],
        [7, 3, 2],
        [2, 4, 4]]])

# Stacking

In [36]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print("#"*10)
print(b)

[[1 2]
 [3 4]]
##########
[[5 6]
 [7 8]]


In [38]:
np.vstack([a,b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [39]:
np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# Indexing and slicing row[row,col]

In [51]:
r = np.random.randint(1,10,16).reshape(4,4)
r

array([[8, 4, 3, 6],
       [6, 5, 2, 2],
       [1, 2, 7, 9],
       [5, 9, 5, 5]])

In [54]:
# print(r[0])
# print(r[-1])
# print(r[:])
# print(r[:,:])
# print(r[0,1])
# print(r[0,0])
# print(r[::-1,::-1])
print(r[1:3,1:3])
# print(r[:,:2])

[[5 2]
 [2 7]]


# Create an array of 49 (7x7) matrix and replace all the values above diagonal to zero and later replace all the values below diagonal to zero

In [68]:
m = np.random.randint(1,10,49).reshape(7,7)
m

array([[2, 5, 8, 1, 5, 1, 9],
       [5, 3, 5, 9, 8, 6, 5],
       [5, 5, 6, 8, 2, 3, 2],
       [1, 3, 9, 8, 8, 2, 6],
       [2, 6, 1, 1, 6, 3, 4],
       [1, 4, 9, 6, 1, 6, 9],
       [6, 1, 2, 4, 9, 9, 4]])

In [67]:
cnt = 1
for row in m:
    row[cnt:] = 0
    cnt +=1
m

array([[5, 0, 0, 0, 0, 0, 0],
       [9, 2, 0, 0, 0, 0, 0],
       [3, 4, 3, 0, 0, 0, 0],
       [3, 9, 9, 3, 0, 0, 0],
       [5, 5, 6, 5, 7, 0, 0],
       [1, 9, 8, 8, 9, 8, 0],
       [9, 6, 1, 2, 1, 4, 1]])

In [69]:
cnt = 1
for row in m:
    row[:cnt-1] = 0
    cnt +=1
m

array([[2, 5, 8, 1, 5, 1, 9],
       [0, 3, 5, 9, 8, 6, 5],
       [0, 0, 6, 8, 2, 3, 2],
       [0, 0, 0, 8, 8, 2, 6],
       [0, 0, 0, 0, 6, 3, 4],
       [0, 0, 0, 0, 0, 6, 9],
       [0, 0, 0, 0, 0, 0, 4]])

### Filtering values

In [71]:
m = np.random.randint(0,90,60).reshape(10,6)
m

array([[46,  2, 20,  7, 43, 45],
       [48, 50,  9, 23, 30, 86],
       [22, 52, 58, 82, 23, 26],
       [22, 57, 12, 51, 40, 79],
       [30,  4, 72, 31, 84, 56],
       [85, 56, 85, 68, 10,  7],
       [50, 36,  2, 47, 18, 20],
       [15, 86, 11, 79, 86,  2],
       [18, 80, 68, 47, 25, 33],
       [ 9, 18, 11, 71,  8, 60]])

###### using where function

In [75]:
idx = np.where(m<30)
idx

(array([0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 4, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 9,
        9, 9, 9], dtype=int64),
 array([1, 2, 3, 2, 3, 0, 4, 5, 0, 2, 1, 4, 5, 2, 4, 5, 0, 2, 5, 0, 4, 0,
        1, 2, 4], dtype=int64))

In [79]:
m[idx][5]

22

In [77]:
m[idx].size

25

###### multiple conditions

In [82]:
idx = np.where((m>30) & (m<60) )
m[idx]

array([46, 43, 45, 48, 50, 52, 58, 57, 51, 40, 31, 56, 56, 50, 36, 47, 47,
       33])

###### Another way to filter

In [80]:
m[m<30]

array([ 2, 20,  7,  9, 23, 22, 23, 26, 22, 12,  4, 10,  7,  2, 18, 20, 15,
       11,  2, 18, 25,  9, 18, 11,  8])

In [ ]:
m = np.random.randint(1,10,49).reshape(7,7)
m

###### multiple conditions

In [83]:
m[(m>30) & (m<60) ]

array([46, 43, 45, 48, 50, 52, 58, 57, 51, 40, 31, 56, 56, 50, 36, 47, 47,
       33])

# Applying statistics functions

In [84]:
m = np.random.randint(0,10,20).reshape(5,4)
m

array([[7, 8, 1, 4],
       [2, 7, 0, 6],
       [5, 6, 7, 4],
       [3, 1, 8, 7],
       [2, 2, 7, 0]])

In [86]:
print(m.sum())
print(m.min())

87
0


In [87]:
print(m.sum(axis=0))

[19 24 23 21]


In [91]:
print(m.std(axis=0))

[1.93907194 2.78567766 3.38230691 2.4       ]


In [92]:
m.std()

2.7069355367278325

In [93]:
print(m.std(axis=1))

[2.73861279 2.86138079 1.11803399 2.86138079 2.58602011]


In [94]:
print(m.mean())

4.35


In [95]:
print(m.mean(axis=0))

[3.8 4.8 4.6 4.2]


In [96]:
print(m.var(axis=0))

[ 3.76  7.76 11.44  5.76]


In [97]:
print(m[:,1].var(axis=0))

7.76


In [98]:
print(m[:,-1].var(axis=0))

5.76


In [99]:
print(m[-1].var(axis=0))

6.6875


###### Transpose

In [89]:
m.T

array([[7, 2, 5, 3, 2],
       [8, 7, 6, 1, 2],
       [1, 0, 7, 8, 7],
       [4, 6, 4, 7, 0]])

#### linspace

In [104]:
np.linspace(-1,-2)

array([-1.        , -1.02040816, -1.04081633, -1.06122449, -1.08163265,
       -1.10204082, -1.12244898, -1.14285714, -1.16326531, -1.18367347,
       -1.20408163, -1.2244898 , -1.24489796, -1.26530612, -1.28571429,
       -1.30612245, -1.32653061, -1.34693878, -1.36734694, -1.3877551 ,
       -1.40816327, -1.42857143, -1.44897959, -1.46938776, -1.48979592,
       -1.51020408, -1.53061224, -1.55102041, -1.57142857, -1.59183673,
       -1.6122449 , -1.63265306, -1.65306122, -1.67346939, -1.69387755,
       -1.71428571, -1.73469388, -1.75510204, -1.7755102 , -1.79591837,
       -1.81632653, -1.83673469, -1.85714286, -1.87755102, -1.89795918,
       -1.91836735, -1.93877551, -1.95918367, -1.97959184, -2.        ])

In [105]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])